# Generated by Django 4.0.4 on 2022-05-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wychowawca', models.CharField(max_length=400)),
                ('nazwa_klasy', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasy',
            },
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=400)),
                ('nazwisko', models.CharField(max_length=400)),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzienniczek.klasa')),
            ],
            options={
                'verbose_name': 'Uczeń',
                'verbose_name_plural': 'Uczniowie',
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.CharField(max_length=100)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzienniczek.przedmiot')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzienniczek.uczen')),
            ],
            options={
                'verbose_name': 'Ocena',
                'verbose_name_plural': 'Oceny',
            },
        ),
    ]
